#!/usr/bin/env python3
"""Bootstrap a WCETs.xml for a platform catalogue from an SDF graph's nominal
execution times.

This is a scaffolding convenience, not a measurement.  Real WCETs come from
static analysis or measurement on the actual core; this just produces a
well-formed table (nominal * mode cycle factor) so a new platform can be
exercised end to end.  The generated file carries a header saying so.
"""
import sys, argparse
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from sdf3 import parse_sdf3
from platform import parse_platform

ap = argparse.ArgumentParser()
ap.add_argument("--app", action="append", required=True)
ap.add_argument("--platform", required=True)
ap.add_argument("--patterns", help="also emit entries for pattern components")
ap.add_argument("--checker-scale", type=float, default=0.3,
                help="checker WCET as a fraction of its doer's (default 0.3); "
                     "a placeholder, not a measurement")
ap.add_argument("-o", required=True)
a = ap.parse_args()

plat = parse_platform(a.platform)
seen = {}
for app in a.app:
    for act in parse_sdf3(app).actors:
        seen.setdefault(act.type, act.exec_time)

if a.patterns:
    import yaml
    doc = yaml.safe_load(Path(a.patterns).read_text())
    extra = {}
    for rec in doc["patterns"]:
        for c in rec.get("components") or []:
            wt = str(c.get("wcet_type", "<owner>"))
            for t, base in list(seen.items()):
                name = wt.replace("<owner>", t)
                if name not in seen:
                    scale = a.checker_scale if name != t else 1.0
                    extra[name] = max(1, round(base * scale))
    seen.update(extra)

L = ['<WCET_table>',
     '<!-- GENERATED by mkwcets.py: nominal exec time scaled by mode cycle',
     '     factor. Scaffolding only - replace with measured or analysed WCETs',
     '     before drawing any conclusion from a result. -->']
for t, base in sorted(seen.items()):
    L.append(f'  <mapping task_type="{t}">')
    for ct in plat.core_types:
        for m in ct.modes:
            L.append(f'    <wcet processor="{ct.model}" mode="{m.name}" '
                     f'wcet="{max(1, round(base * m.cycle))}"/>')
    L.append('  </mapping>')
L.append('</WCET_table>')
Path(a.o).write_text("\n".join(L) + "\n")
print(f"wrote {a.o}: {len(seen)} task types x {sum(len(c.modes) for c in plat.core_types)} (core,mode) pairs")
